# 07.04.2022 Eike Doose

sqlcmd -S localhost\SDMSCLOUD1 -U SA -P Admin00! -Q "RESTORE DATABASE [CLOUD1MASTER1] FROM  DISK = N'C:\install\StarkeDMS-latest\SQL-DB-CLOUD1MASTER1.bak' WITH  FILE = 1,  MOVE N'CLOUD1MASTER1_Pri' TO N'D:\dms-data\sql\MSSQL15.SDMSCLOUD1\MSSQL\DATA\CLOUD1MASTER1_Pri.mdf',  MOVE N'CLOUD1MASTER1_Dat' TO N'D:\dms-data\sql\MSSQL15.SDMSCLOUD1\MSSQL\DATA\CLOUD1MASTER1_Dat.ndf',  MOVE N'CLOUD1MASTER1_txt' TO N'D:\dms-data\sql\MSSQL15.SDMSCLOUD1\MSSQL\DATA\CLOUD1MASTER1_Txt.ndf',  MOVE N'CLOUD1MASTER1_Log' TO N'D:\dms-data\sql\MSSQL15.SDMSCLOUD1\MSSQL\DATA\CLOUD1MASTER1_Log.ldf',  NOUNLOAD,  REPLACE,  STATS = 5;"

sqlcmd -S localhost\SDMSCLOUD1 -U SA -P Admin00! -Q "ALTER DATABASE CLOUD1MASTER1 SET SINGLE_USER WITH ROLLBACK IMMEDIATE;"
sqlcmd -S localhost\SDMSCLOUD1 -U SA -P Admin00! -Q "ALTER DATABASE CLOUD1MASTER1 MODIFY FILE (NAME=N'CLOUD1MASTER1_Pri', NEWNAME=N'CLOUDtaest_pri');"
sqlcmd -S localhost\SDMSCLOUD1 -U SA -P Admin00! -Q "ALTER DATABASE CLOUD1MASTER1 MODIFY FILE (NAME=N'CLOUD1MASTER1_Log', NEWNAME=N'CLOUDtaest_log');"
sqlcmd -S localhost\SDMSCLOUD1 -U SA -P Admin00! -Q "ALTER DATABASE CLOUD1MASTER1 MODIFY FILE (NAME=N'CLOUD1MASTER1_Dat', NEWNAME=N'CLOUDtaest_dat');"
sqlcmd -S localhost\SDMSCLOUD1 -U SA -P Admin00! -Q "ALTER DATABASE CLOUD1MASTER1 MODIFY FILE (NAME=N'CLOUD1MASTER1_Txt', NEWNAME=N'CLOUDtaest_txt');"
sqlcmd -S localhost\SDMSCLOUD1 -U SA -P Admin00! -Q "EXEC master.dbo.sp_detach_db @dbname = N'CLOUD1MASTER1'"

Rename-Item D:\dms-data\sql\MSSQL15.SDMSCLOUD1\MSSQL\DATA\CLOUD1MASTER1_Pri.mdf D:\dms-data\sql\MSSQL15.SDMSCLOUD1\MSSQL\DATA\CLOUDtaest_pri.mdf
Rename-Item D:\dms-data\sql\MSSQL15.SDMSCLOUD1\MSSQL\DATA\CLOUD1MASTER1_log.ldf D:\dms-data\sql\MSSQL15.SDMSCLOUD1\MSSQL\DATA\CLOUDtaest_log.ldf
Rename-Item D:\dms-data\sql\MSSQL15.SDMSCLOUD1\MSSQL\DATA\CLOUD1MASTER1_dat.ndf D:\dms-data\sql\MSSQL15.SDMSCLOUD1\MSSQL\DATA\CLOUDtaest_dat.ndf
Rename-Item D:\dms-data\sql\MSSQL15.SDMSCLOUD1\MSSQL\DATA\CLOUD1MASTER1_txt.ndf D:\dms-data\sql\MSSQL15.SDMSCLOUD1\MSSQL\DATA\CLOUDtaest_txt.ndf

sqlcmd -S localhost\SDMSCLOUD1 -U SA -P Admin00! -Q "CREATE DATABASE CLOUDtaest ON ( FILENAME = N'D:\dms-data\sql\MSSQL15.SDMSCLOUD1\MSSQL\DATA\CLOUDtaest_pri.mdf' ), ( FILENAME = N'D:\dms-data\sql\MSSQL15.SDMSCLOUD1\MSSQL\DATA\CLOUDtaest_log.ldf' ), ( FILENAME = N'D:\dms-data\sql\MSSQL15.SDMSCLOUD1\MSSQL\DATA\CLOUDtaest_dat.ndf' ), ( FILENAME = N'D:\dms-data\sql\MSSQL15.SDMSCLOUD1\MSSQL\DATA\CLOUDtaest_txt.ndf' ) FOR ATTACH;"
sqlcmd -S localhost\SDMSCLOUD1 -U SA -P Admin00! -Q "ALTER DATABASE CLOUDtaest SET MULTI_USER;"